/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cafe.gui.dialogs;

import com.cafe.dao.PaymentDAO;
import com.cafe.dao.PaymentDAOImpl;
import com.cafe.model.Payment;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author justlowkee
 */
public class PaymentDialog extends javax.swing.JFrame {
    
    public interface PaymentCallback {
        void onPaymentComplete(Payment payment);
        void onPaymentCancelled();
    }
    
    private PaymentDAO paymentDAO;
    private double totalAmount;
    private Long orderId;
    private Payment processedPayment;
    private DecimalFormat currencyFormat;
    private ButtonGroup paymentMethodGroup;
    private PaymentCallback callback;

    /**
     * Creates new form PaymentDialog
     */
    public PaymentDialog() {
        initComponents();
        initializePaymentDialog();
    }
    
    /**
     * Creates new form PaymentDialog with order details
     */
    public PaymentDialog(Long orderId, double totalAmount) {
        this.orderId = orderId;
        this.totalAmount = totalAmount;
        initComponents();
        initializePaymentDialog();
        setupOrderDetails();
    }
    
    /**
     * Creates new form PaymentDialog with order details and callback
     */
    public PaymentDialog(Long orderId, double totalAmount, PaymentCallback callback) {
        this.orderId = orderId;
        this.totalAmount = totalAmount;
        this.callback = callback;
        initComponents();
        initializePaymentDialog();
        setupOrderDetails();
    }
    
    private void initializePaymentDialog() {
        paymentDAO = new PaymentDAOImpl();
        currencyFormat = new DecimalFormat("$#,##0.00");
        
        paymentMethodGroup = new ButtonGroup();
        paymentMethodGroup.add(jRadioButton1); // Cash
        paymentMethodGroup.add(jRadioButton2); // Paywave/Eftpos
        
        jRadioButton1.setSelected(true);
        
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                calculateChange();
            }
        });
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    private void setupOrderDetails() {
        jLabel2.setText(currencyFormat.format(totalAmount));
        updateCashFieldVisibility();
    }
    
    private void updateCashFieldVisibility() {
        boolean isCash = jRadioButton1.isSelected();
        jLabel4.setVisible(isCash);
        jTextField1.setVisible(isCash);
        jLabel5.setVisible(isCash);
        jLabel6.setVisible(isCash);
        
        if (!isCash) {
            jLabel6.setText("$0.00");
        }
    }
    
    private void calculateChange() {
        if (jRadioButton1.isSelected()) {
            try {
                double cashReceived = Double.parseDouble(jTextField1.getText());
                double change = cashReceived - totalAmount;
                jLabel6.setText(currencyFormat.format(Math.max(0, change)));
            } catch (NumberFormatException e) {
                jLabel6.setText("$0.00");
            }
        }
    }
    
    public Payment getProcessedPayment() {
        return processedPayment;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment Processing");
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("October Compressed Tamil", 1, 18)); // NOI18N
        jLabel1.setText("Text Amount:");

        jLabel2.setFont(new java.awt.Font("October Compressed Tamil", 1, 18)); // NOI18N
        jLabel2.setText("$ 0.00");

        jLabel3.setFont(new java.awt.Font("October Compressed Tamil", 1, 18)); // NOI18N
        jLabel3.setText("Payment Amount:");

        jRadioButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jRadioButton1.setText("Cash");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jRadioButton2.setText("Paywave / Eftpos");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("October Compressed Tamil", 1, 18)); // NOI18N
        jLabel4.setText("Cash Received:");

        jTextField1.setFont(new java.awt.Font("October Compressed Tamil", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("October Compressed Tamil", 1, 18)); // NOI18N
        jLabel5.setText("Change:");

        jLabel6.setFont(new java.awt.Font("October Compressed Tamil", 1, 18)); // NOI18N
        jLabel6.setText("$ 0.00");

        jButton1.setText("Process Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        updateCashFieldVisibility();
        calculateChange();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (callback != null) {
            callback.onPaymentCancelled();
        }
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        updateCashFieldVisibility();
        calculateChange();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        processPayment();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void processPayment() {
        try {
            String paymentMethod = jRadioButton1.isSelected() ? "CASH" : "PAYWAVE";
            double changeAmount = 0.0;
            
            if (jRadioButton1.isSelected()) {
                try {
                    double cashReceived = Double.parseDouble(jTextField1.getText());
                    if (cashReceived < totalAmount) {
                        JOptionPane.showMessageDialog(this, 
                            "Insufficient cash received. Please enter at least " + currencyFormat.format(totalAmount),
                            "Payment Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    changeAmount = cashReceived - totalAmount;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, 
                        "Please enter a valid cash amount.",
                        "Payment Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            Payment payment = new Payment(orderId, totalAmount, paymentMethod);
            payment.setChangeAmount(changeAmount);
            payment.setStatus("COMPLETED");
            
            processedPayment = paymentDAO.createPayment(payment);
            
            if (callback != null) {
                callback.onPaymentComplete(processedPayment);
            }
            
            dispose();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Error processing payment: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Unexpected error: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
